Student_name=input("Enter the student name:")
Student_age=int(input("Enter the age of the student: "))
Course_rating=float(input("Enter the Course rating:"))
print(f"Student Name: {Student_name}")
print(f"Student Age: {Student_age}")
print(f"Course Ratings: {Course_rating}")
print(type(Student_name))
print(type(Student_age))
print(type(Course_rating))